version: '3.9'
services:
  server:
    build: .
    ports:
      - '3333:3333'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: